# Generated by Django 6.0.7 on 2026-08-02 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_seed_contact_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Numer telefonu musi mieć 9 cyfr, opcjonalnie z prefiksem +48.",
                        regex="^(\\+?48[\\s-]?)?(\\d[\\s-]?){8}\\d$",
                    )
                ],
            ),
        ),
    ]
